### ISSUE TITLE
Phones and iPad not detected?

### ISSUE THREAD

**Issue by DavidFW1960** [mudape/iphonedetect#1]
I added the repo from HACS today. I am not getting any device trackers created.
```
device_tracker:
  - platform: fritz
    host: !secret my_fritz_host
    consider_home: 180
    new_device_defaults:
      track_new_devices: false
      hide_if_away: false
  - platform: iphonedetect
    consider_home: 60
    hosts:
      hostname1: !secret david_iphone
      hostname2: !secret david_ipad
      hostname3: !secret liz_iphone
```
I am using secrets... is that the problem?

**Comment by mudape** [comment]
Hi David,Thanks for reporting. 
I haven't actually tried with secrets, how did you enter the IP address?Will try as soon as possible (on the road at the moment)Are the hostnames written to known_devices.yaml?

    	
    	

    	First, there was nothing. Which exploded. - If anything can go wrong, it will. 
    
  




On Tue, Jul 2, 2019 at 5:30 AM +0200, "DavidFW1960" <notifications@github.com> wrote:












I added the repo from HACS today. I am not getting any device trackers created.
device_tracker:
  - platform: fritz
    host: !secret my_fritz_host
    consider_home: 180
    new_device_defaults:
      track_new_devices: false
      hide_if_away: false
  - platform: iphonedetect
    consider_home: 60
    hosts:
      hostname1: !secret david_iphone
      hostname2: !secret david_ipad
      hostname3: !secret liz_iphone



I am using secrets... is that the problem?

**Comment by DavidFW1960** [comment]
Hi thanks for the response. 

No nothing is added to the known_devices yaml at all. Also tried removing secrets and just specifying the static IP address.... nothing... I am running Hass.io

**Comment by mudape** [comment]
Hi David,
Strange, works fine here even with IP in secrets. 
Also I removed entries in known_devices.yaml, restarted HA and they reappear once they are on the network again. 

Can you add debug logging for custom_components.iphonedetect and see if you get any output?

**Comment by mudape** [comment]
Which HA release are you running?
This only works on 0.94+ on a Linux host

**Comment by DavidFW1960** [comment]
I am running Debian Buster+docker+hassio. Home Assistant is 0.95.4
I did a generic Linux install of Hass.io about a year ago on Debian Stretch but upgraded to buster a few weeks ago.

I'll add debug logging

**Comment by DavidFW1960** [comment]
Actually.... hold the phone.... hahaha
I DO see now a hostname3: in known devices. That is my Wife's iPhone.
I am running iOS13 public beta 1 on mine... I wonder if that is the issue?

**Comment by DavidFW1960** [comment]
```
2019-07-04 11:15:03 DEBUG (SyncWorker_7) [custom_components.iphonedetect.device_tracker] Started iphonedetect with interval=0:00:12 on hosts: 10.90.11.33,10.90.11.18,10.90.11.41
```
But still only shows hostname3.

I manually added hostname1 and 2 to known devices and will restart and see what happens.

**Comment by DavidFW1960** [comment]
Seems manually adding them was the trick
![image](https://user-images.githubusercontent.com/36390762/60633459-1a74a300-9e4e-11e9-8672-6cfefed96ae6.png)

**Comment by BellaRosa1** [comment]
Can a picture be added to this to show the person?

**Comment by mudape** [comment]
Hi @BellaRosa1,

Indeed, Home Assistant already have multiple ways do do that.
E.g. you can add picture in the [known_devices.yaml](https://www.home-assistant.io/components/device_tracker/#known_devicesyaml) or (like I've done) use a [picture-entity card](https://www.home-assistant.io/lovelace/picture-entity/) in lovelace.

```yaml
cards:
  - entity: device_tracker.hostname
    show_name: false
    show_state: false
    state_image:
      home: /local/hostname_home.png
      not_home: /local/hostname_away.png
```
Place the pictures in your /config/www folder

There's also the [person](https://www.home-assistant.io/components/person/) integration which I haven't started using yet.

**Comment by mudape** [comment]
@DavidFW1960 
Is it working for you now?
I don't have any iOS 13 devices so can't test myself

**Comment by BellaRosa1** [comment]
I will have to let you know later, we had a major storm and lost internet,  Thanks for the quick response.



Mickie Pitts

**Comment by Martinvdm** [comment]
Is the known_devices.yaml still in use? i thought it was depricated and now the .storage folder is used. I tried this component but no devices found after reboot

**Comment by mudape** [comment]
It's still used. 
Once a device comes back "online" it should be added. 

Hostname must be in lower case iirc

**Comment by Martinvdm** [comment]
Nope. Device exists in known_devices but not visangel in ha

**Comment by mudape** [comment]
Are you using Lovelace as UI?
Check under Unused entities, the Device Tracker card.

Else, do you see the device in States (the <> link)?
Should be there as device_tracker.<the hostname you entered>

**Comment by DavidFW1960** [comment]
> @DavidFW1960
> Is it working for you now?
> I don't have any iOS 13 devices so can't test myself

Yes working but I had to manually add the device tracker to known_devices.yaml
Once I did that it is working fine.

Thanks.

**Comment by DavidFW1960** [comment]
> Can a picture be added to this to show the person?

I add it to my Person and have a picture configured for the person.
![image](https://user-images.githubusercontent.com/36390762/60749104-a6b2d180-9fd8-11e9-92f0-5f792488ddf7.png)

**Comment by DavidFW1960** [comment]
> Is the known_devices.yaml still in use?

It is for this custom_component. Not everything is migrated yet.

**Comment by DavidFW1960** [comment]
> Nope. Device exists in known_devices but not visangel in ha sensor list

It's not a sensor.
See my screenshot above...
device_tracker.hostname1 

If it's in known_devices it will be listed in states

**Comment by Martinvdm** [comment]
Nope it is not in the states view, No device at all

**Comment by DavidFW1960** [comment]
@Martinvdm mine didn’t get detected either but manually adding to known_devices.yaml and they started working after next restart of HA.

It looks like this in my known_devices file:

```
hostname1:
  hide_if_away: false
  icon:
  mac:
  name: hostname1
  picture:
  track: true
```

**Comment by Martinvdm** [comment]
@DavidFW1960 
i do understand you, devices are in known_devices already.
```
iphone_van_martin_detect:
  hide_if_away: false
  icon:
  mac:
  name: iphone_van_martin_detect
  picture:
  track: false

iphone_van_wife_detect:
  hide_if_away: false
  icon:
  mac:
  name: iphone_van_wife_detect
  picture:
  track: false
```
