### ISSUE TITLE
Probe returning away on all iphones

### ISSUE THREAD

**Issue by mtthidoteu** [mudape/iphonedetect#119]
Hi,
I am opening an issue as I can't find any reason this is not working and behaving as such:
Config:
```
device_tracker:
  - platform: iphonedetect
    consider_home: 60
    scan_interval: 12
    new_device_defaults:
      track_new_devices: true
    hosts:
      iphone-one: 192.168.0.21
      iphone-two: 192.168.0.22
      iphone-three: 192.168.0.18
      ```
I am able to ping the devices from my Home Assistant installation which is not a different subnet but firewall rules are setup correctly. After enabling debug logs:
```
2024-08-30 11:14:17.323 DEBUG (SyncWorker_9) [custom_components.iphonedetect.device_tracker] Probe sent to iphone-one on 192.168.0.21
2024-08-30 11:14:17.326 DEBUG (SyncWorker_9) [custom_components.iphonedetect.device_tracker] Probe sent to iphone-two on 192.168.0.22
2024-08-30 11:14:17.327 DEBUG (SyncWorker_9) [custom_components.iphonedetect.device_tracker] Probe sent to iphone-three on 192.168.0.18
2024-08-30 11:14:17.341 DEBUG (SyncWorker_9) [custom_components.iphonedetect.device_tracker] Device iphone-one on 192.168.0.21 is AWAY
2024-08-30 11:14:17.341 DEBUG (SyncWorker_9) [custom_components.iphonedetect.device_tracker] Device iphone-two on 192.168.0.22 is AWAY
2024-08-30 11:14:17.341 DEBUG (SyncWorker_9) [custom_components.iphonedetect.device_tracker] Device iphone-three on 192.168.0.18 is AWAY```

Is there anything I am obviously missing?

**Comment by bbiggscs** [comment]
Having the same issue with the same debug information. HA can ping the devices, they are even on the same subnet and are having no issues communicating otherwise. Also have almost identical config in YAML and had been working fine until I recently updated HA to the following:

Core
2024.9.1
Supervisor
2024.09.1
Operating System
11.5
Frontend
20240906.0

**Comment by mudape** [comment]
Hi,

> I am able to ping the devices from my Home Assistant installation which is not a different subnet but firewall rules are setup correctly.

This integration doesn't "ping" (as in ICMP) the tracked device, it sends a message on UDP 5353 to the IP of the device.

**Comment by secz0r** [comment]
I also have the same problem. I'm new to this integration so I might be missing something else of course.

My config:
```
device_tracker:
  - platform: iphonedetect
    consider_home: 60
    scan_interval: 10
    new_device_defaults:
      track_new_devices: true
    hosts:
      xxx_iPhone_tracker: 10.0.1.30
      yyy_iphone_tracker: 10.0.1.31
      zzz_iphone_tracker: 10.0.1.32
```

Debug log:
```
2024-10-29 20:47:29.541 DEBUG (SyncWorker_63) [custom_components.iphonedetect.device_tracker] Device xxx_iPhone_tracker on 10.0.1.30 is AWAY
2024-10-29 20:47:29.541 DEBUG (SyncWorker_63) [custom_components.iphonedetect.device_tracker] Device yyy_iphone_tracker on 10.0.1.31 is AWAY
2024-10-29 20:47:29.541 DEBUG (SyncWorker_63) [custom_components.iphonedetect.device_tracker] Device zzz_iphone_tracker on 10.0.1.32 is AWAY
```
