### ISSUE TITLE
The see service is not supported for this entity

### ISSUE THREAD

**Issue by rekatab** [mudape/iphonedetect#124]
When iPhone Device Tracker detects an iphone, which is configured with its IPv4-Adress in configuration.yaml, the following error is written to Home Assistant Core log:

`Logger: homeassistant.components.device_tracker
Quelle: components/device_tracker/legacy.py:676
Integration: Geräte-Tracker (Dokumentation, Probleme)
Erstmals aufgetreten: 15:01:42 (195 Vorkommnisse)
Zuletzt protokolliert: 15:48:31

The see service is not supported for this entity device_tracker.hostname1`

The entity device_tracker.hostname1 is not set!

**Comment by mudape** [comment]
Hi @rekatab 
Looks like the entity doesn't exist, was it not added to known_devices.yaml?
Note that track must be set to true

```yaml
hostname1:
  icon:
  mac:
  name: hostname1
  picture:
  track: true
```

**Comment by rekatab** [comment]
there is any known_devices.yaml file.
The device_tracker documentation says about the file:
"As of 0.94 known_devices.yaml is being phased out and no longer used by all trackers."

Shall I create the file by hand? 🤔

**Comment by mudape** [comment]
Strange that there is no known_devices.yaml, it's still being created by HA on a new install.
However, if you install the latest release of this integration, it too isn't using that file any longer.

Please give it a try

**Comment by ildar170975** [comment]
"known_devices.yaml" can be created automatically if you call `device_tracker.see` service for ANY even non-existing entity like `device.tracker.pet` - then this entity will be created with set state/attributes and "known_devices.yaml" will be created (if was not yet) and contain a corr. entry.

**Comment by mudape** [comment]
Found https://github.com/home-assistant/home-assistant.io/issues/25103

Did you set track_new_devices ?
```yaml
device_tracker:
  - platform: iphonedetect
    consider_home: 60
    scan_interval: 12
    new_device_defaults:
      track_new_devices: true
    hosts:
      hostname1: 192.168.0.17
      hostname2: 192.168.0.24
```

Do see that when 'device_tracker.legacy.remove_device_from_config' clears devices known_devices.yaml is left with an empty dict which seems to cause confusion.

I think we can close this as the latest release is set up via UI, what do you think?
