### ISSUE TITLE
'The YAML configuration is being removed' but iPhone Device Tracker no longer works if you delete the settings in the YAML files

### ISSUE THREAD

**Issue by liuk4friends** [mudape/iphonedetect#135]
- Hardware: Rpi4B 4GB
- Core: 2025.1.2
- Supervisor: 2024.12.3
- Operating System:14.1
- Frontend: 20250109.0
- iPhone Device Tracker: 2.4.0

The new iPhone Device Tracker 2.4.0 introduces the ability to configure via UI. Thanks for this great feature!

However, after installing version 2.4.0, if I delete the iphonedetect settings from 'configuration.yaml' and form 'device_tracker.yaml', upon reboot the four iPhones in our family disappear from Home Assistant.

If I restore the settings in 'configuration.yaml' / 'device_tracker.yaml' and then reboot, iPhone Device Tracker starts working again.

Below I transcribe the content of 'configuration.yaml' :

```
device_tracker: !include /config/includes/device_tracker.yaml
```

and of 'device_tracker.yaml'  :

```
  - platform: iphonedetect
    scan_interval: 12
    consider_home: 120
    new_device_defaults:
      track_new_devices: false
    hosts:
      hostname1: 192.168.178.**
      hostname2: 192.168.178.**
      hostname3: 192.168.178.**
      hostname4: 192.168.178.**
```

Thank you for your kind attention and support

**Comment by ikorpershoek** [comment]
same here

**Comment by mudape** [comment]
Hi,

I didn't think of using split configuration, looks like the import fails somehow. 

Just to ask, you did restart HA after installing 2.4.0 and then deleted iphonedetect from config? Two restarts

The import should remove tracked devices from know_devices.yaml so that the entity can keep its name.

**Comment by pawelaugustyn** [comment]
It worked for me by removing entities from the configuration.yaml _before_ the restart and re-adding them in the UI

**Comment by mudape** [comment]
I tried installing 1.4.2 with a split configuration and after struggling with known_devices got it to work.
Upgrading to 2.4.0 did work: entities were imported and remained after removing iphonedetect from YAML configuration.
Weird!

I see you have "track_new_devices" set to False.
What is the content, if any, in the known_devices.yaml file?

**Comment by mudape** [comment]
By entity ID do you mean the device_tracker._name_ changed to device_tracker._name_2_ ?
I was kind of hoping that the import from YAML should've handled that...

My automations are based on the Person Home/Away (they might have several device_tracker's) so didn't notice

**Comment by raspman** [comment]
Yes, exactly.

**Comment by mudape** [comment]
As far as I can tell the old names are preserved by still being in the known_devices.yaml file.
Do you have other integrations using those?

After upgrading from the earlier version of iphonedetect and restarting, the YAML-configuration should be imported **after** HA has  completely loaded.
Then first remove the entries in known_device before creating the "new" entities allowing the name to be the same.
Names are slugified though, so "My iPhone" becomes "my_iphone"

**Comment by raspman** [comment]
I didn't remove the know_devices first...can I delete that file completely now?  I just want to get rid of the "old" entities as I can't delete them...

**Comment by mudape** [comment]
Yes, that should work fine.
I would create a backup first, of the file content at least

**Comment by raspman** [comment]
I deleted known_device.yaml, but the old entities are still showing.....can't figure out how to remove them

**Comment by mudape** [comment]
Sorry to hear that raspman, don't know what's going on.
Some other integration, like the HA app, that has the name?

If you can access /config/.storage and search for the names in the files there, maybe some hint might be found

**Comment by raspman** [comment]
It's gone now :)  Maybe it just took some time..anyways, thanks again for the great service you provide!

**Comment by liuk4friends** [comment]
> Hi,
> 
> I didn't think of using split configuration, looks like the import fails somehow.
> 
> Just to ask, you did restart HA after installing 2.4.0 and then deleted iphonedetect from config? Two restarts
> 
> The import should remove tracked devices from know_devices.yaml so that the entity can keep its name.

First of all, thank you again for your work.
About your question, I've installed 2.4.0, then I've deleted yaml configuration, then I've restarted HassOS

**Comment by liuk4friends** [comment]
> I tried installing 1.4.2 with a split configuration and after struggling with known_devices got it to work. Upgrading to 2.4.0 did work: entities were imported and remained after removing iphonedetect from YAML configuration. Weird!
> 
> I see you have "track_new_devices" set to False. What is the content, if any, in the known_devices.yaml file?

I didn't check this file after installing 2.4.0.
Now its content is this below

```
{}

```

From a previous backup (2025.01.14) the content was:
```
hostname1:
  icon: mdi:cellphone
  mac: **:**:**:**:**:**
  name: hostname1 #iPhone 15 Pro di Luca
  #picture:
  track: true

hostname2:
  icon: mdi:cellphone
  mac: **:**:**:**:**:**
  name: hostname2 #iPhone 12 di Laura
  #picture:
  track: true
  
hostname3:
  icon: mdi:cellphone
  mac: **:**:**:**:**:**
  name: hostname3 #iPhone 13 Pro di Elena
  #picture:
  track: true

hostname4:
  icon: mdi:cellphone
  mac: **:**:**:**:**:**
  name: hostname4 #iPhone 11 Pro di Chiara
  #picture:
  track: true
```
