### ISSUE TITLE
iPhonedetect 1.2.2 detects phone as present when away

### ISSUE THREAD

**Issue by gieljnssns** [mudape/iphonedetect#21]
As you asked me, a new issue...
I'm on v1.2.2 and iphonedetect detects phone as present when away.
Hassio generic install on an intel nuc (Buster)
Wifi connected:
```
bash-5.0# ip n|grep 192.168.79.8
192.168.79.8 dev eno1 lladdr xx:xx:xx:xx:29:2f ref 1 used 0/0/0 probes 1 REACHABLE
bash-5.0# ip n|grep 192.168.79.8
192.168.79.8 dev eno1 lladdr xx:xx:xx:xx:29:2f ref 1 used 0/0/0 probes 1 DELAY
bash-5.0# ip n|grep 192.168.79.8
192.168.79.8 dev eno1 lladdr xx:xx:xx:xx:29:2f ref 1 used 0/0/0 probes 1 PROBE
```
not connected:
```
bash-5.0# ip n|grep 192.168.79.8
192.168.79.8 dev eno1  used 0/0/0 probes 3 FAILED
bash-5.0# ip n|grep 192.168.79.8
192.168.79.8 dev eno1  used 0/0/0 probes 6 FAILED
bash-5.0# arp -na|grep 192.168.79.8
? (192.168.79.8) at <incomplete> on eno1
bash-5.0# arp -na|grep 192.168.79.8
? (192.168.79.8) at <incomplete> on eno1
```
connected again:
```
bash-5.0# arp -na|grep 192.168.79.8
? (192.168.79.8) at xx:xx:xx:xx:29:2f [ether] on eno1
```

**Comment by mudape** [comment]
Thanks @gieljnssns,

Looks like it should work... If a MAC can't be found the entity should be set not_home.
What time have you set for `consider_home`?

Are you using the Person component?
Point being that maybe another entity has the person as home.

**Comment by gieljnssns** [comment]
This is my config:
```
  - platform: iphonedetect
    consider_home: 60
    new_device_defaults:
      track_new_devices: true
      hide_if_away: false
    hosts:
      gphone_detect: 192.168.79.8
      mphone_detect: 192.168.79.9
      nphone_detect: 192.168.79.12
      fphone_detect: 192.168.79.13
```

**Comment by gieljnssns** [comment]
I made an extra custom_component from v2.2.0  iphone_detect2
config:
```
  - platform: iphonedetect2
    consider_home: 60
    new_device_defaults:
      track_new_devices: true
      hide_if_away: false
    hosts:
      gphone_detect_2: 192.168.79.8
      mphone_detect_2: 192.168.79.9
      nphone_detect_2: 192.168.79.12
      fphone_detect_2: 192.168.79.13
```
A history graph
```
entities:
  - entity: device_tracker.gphone_detect
    name: 1.1.0gPhone
  - entity: device_tracker.gphone_detect_2
    name: 2.2.0gPhone

refresh_interval: 0
title: Vergelijking iphone_detect
type: history-graph
hours_to_show: 1
```
![Schermafbeelding 2020-02-04 om 15 55 15](https://user-images.githubusercontent.com/17234951/73755722-bf4dba80-4766-11ea-9cc1-e0898ca9b8ba.png)

**Comment by gieljnssns** [comment]
ip n|grep home:
```
bash-5.0# ip n|grep 192.168.79.8
192.168.79.8 dev eno1 lladdr xxxxxxxxxxxxxx ref 1 used 0/0/0 probes 1 REACHABLE
bash-5.0# ip n|grep 192.168.79.8
192.168.79.8 dev eno1 lladdrxxxxxxxxxxxxxx ref 1 used 0/0/0 probes 1 REACHABLE
bash-5.0# ip n|grep 192.168.79.8
192.168.79.8 dev eno1 lladdr xxxxxxxxxxxxxx ref 1 used 0/0/0 probes 1 DELAY
```
ip n|grep  not home:
```
bash-5.0# ip n|grep 192.168.79.8
192.168.79.8 dev eno1  used 0/0/0 probes 3 FAILED
bash-5.0# ip n|grep 192.168.79.8
192.168.79.8 dev eno1  ref 1 used 0/0/0 probes 5 INCOMPLETE
```

**Comment by gieljnssns** [comment]
arp -na|grep 192.168.79.8 home:
```
bash-5.0# arp -na|grep 192.168.79.8
? (192.168.79.8) at xxxxxxxxxxxxxx [ether] on eno1
bash-5.0# arp -na|grep 192.168.79.8
? (192.168.79.8) at xxxxxxxxxxxxxx [ether] on eno1
```
arp -na|grep 192.168.79.8 not home:
```
bash-5.0# arp -na|grep 192.168.79.8
? (192.168.79.8) at <incomplete> on eno1
bash-5.0# arp -na|grep 192.168.79.8
? (192.168.79.8) at <incomplete> on eno1
bash-5.0# arp -na|grep 192.168.79.8
? (192.168.79.8) at <incomplete> on eno1
```

**Comment by mudape** [comment]
Hi Giel,

Wow thanks, nice debugging!

I've played with another check for MAC address which also works fine for me.
Also, false is returned if no MAC is found.
Maybe works better for your platform too?

In the 1.2.2 version, can you please add
```python
import re
```
(at the top where other imports are)

and replace lines 58-71

```python
        try:
            output = subprocess.check_output('ip n|grep '+self.ip_address, shell=True)
            output = output.decode('utf-8').split(' ')
            if len(output[4].split(':')) == 6:
                return True
        except subprocess.CalledProcessError:
            try:
                output = subprocess.check_output('arp -na|grep '+self.ip_address, shell=True)
                output = output.decode('utf-8').split(' ')
                if len(output[3].split(':')) == 6:
                    return True
            except subprocess.CalledProcessError as error:
                _LOGGER.fatal("Could not send command, got %s", error)
                return False
```

with 

```python
        try:
            output = subprocess.check_output('ip neigh show to ' + self.ip_address, shell=True)
            _LOGGER.debug("ip n output for %s is %s", self.ip_address, output.decode('utf-8'))
        except subprocess.CalledProcessError:
            _LOGGER.error("Could not send ip n command")
            try:
                output = subprocess.check_output('arp -na|grep ' + self.ip_address, shell=True)
                _LOGGER.debug("arp output for %s is %s", self.ip_address, output.decode('utf-8'))
            except subprocess.CalledProcessError:
                _LOGGER.fatal("Could not send arp command")
                return False
        finally:
            mac = re.compile(r'(?:[0-9a-fA-F]:?){12}')
            output = output.decode('utf-8')
            if re.findall(mac, output):
                _LOGGER.info("Device %s (%s) is HOME", self.dev_id, self.ip_address)
                return True
            else:
                _LOGGER.info("Device %s (%s) is AWAY", self.dev_id, self.ip_address)
                return False
```

Please note that lots of logging is activated, adjust logger to your needs

```yaml
logger:
  default: error
  logs:
    custom_components.iphonedetect: debug
```

Again, thank you for reporting and investigating!
Please let me know if the code above works.

Cheers
