### ISSUE TITLE
iPhones always listed as not_home

### ISSUE THREAD

**Issue by gieljnssns** [mudape/iphonedetect#3]
This integration is not working for me.
I had to manually add the devices to ```known_devices.yaml``` and now they are always listed as ```not_home``` .
One iPhone on IOS 12.4, one on IOS 13 latest beta
My HA Nuc is on another VLAN as those 2 iPhones, could this be the problem?
My Nuc is running on Debian Buster and Hassio is installed through generic install.
debug
```
2019-08-26 10:05:24 DEBUG (SyncWorker_16) [custom_components.iphonedetect.device_tracker] Started iphonedetect with interval=0:00:12 on hosts: 192.168.69.8,192.168.69.9
```
This is my config
```
  - platform: iphonedetect
    consider_home: 60
    new_device_defaults:
      track_new_devices: true
      hide_if_away: false
    hosts:
      gphone_detect: 192.168.69.8
      mphone_detect: 192.168.69.9
```
```known_devices.yaml```
```
gphone_detect:
  hide_if_away: false
  icon:
  mac:
  name: gPhone detect
  picture:
  track: true

mphone_detect:
  hide_if_away: false
  icon:
  mac:
  name: mPhone detect
  picture:
  track: true
```
