### ISSUE TITLE
Suddenly Stopped Working :-(

### ISSUE THREAD

**Issue by daanvb** [mudape/iphonedetect#4]
I have been using this component flawlessly for a couple of months, then all of a sudden it has stopped working. I had 3 iPhones connected and all now show as away all the time.

Things I have tried:

- I have reinstalled the component
- Hard reset phones
- Restarted Router
- Restarted Pi
- tried adding MAC address
- repeatedly cycled wifi on phones

iPhones show as connected in router settings.

My device tracker config:

```
-platform: bluetooth_tracker

- platform: iphonedetect
  consider_home: 60
  hosts:
    hostname1: 192.168.0.162
    hostname2: 192.168.0.170
    hostname3: 192.168.0.70
```

My known devices config (manually added):

```
hostname1:
  hide_if_away: false
  icon:
  mac: DC:56:E7:A2:A1:AC
  name: hostname1
  picture:
  track: true

hostname2:
  hide_if_away: false
  icon:
  mac:
  name: hostname2
  picture:
  track: true

hostname3:
  hide_if_away: false
  icon:
  mac:
  name: hostname3
  picture:
  track: true
```

Pulling my hair out. Any ideas please?!
