### ISSUE TITLE
Won't detect my iPhone

### ISSUE THREAD

**Issue by SHxKM** [mudape/iphonedetect#46]
From the issue-history this seems like a reliable plugin/script, so I guess I must be doing something wrong.

Network: I have two modem-routers. One is TP-Link "main" which is acting a modem-router; the other is "AP" which is acting simply as an access point - it has its DHCP server turned off so all devices are on the same subnet.

My setup: HA is running dockerized on a computer connected to AP, and that's the same network the iPhone is on when `iphonedetect` won't detect it. To be sure, after giving the iPhone a static IP address on "main",  I have downloaded an app and verified the iPhone indeed has `192.168.1.103`:

<img width="428" alt="Screen Shot 2020-12-13 at 13 12 55" src="https://user-images.githubusercontent.com/6573474/102010164-015f6980-3d45-11eb-90e7-1b75941fda7f.png">

My `configuration.yaml`:

```
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:


group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

device_tracker:
  - platform: iphonedetect
    consider_home: 30
    scan_interval: 12
    new_device_defaults:
      track_new_devices: true
    hosts:
      my_iphone: '192.168.1.103'


logger:
  logs:
    custom_components.iphonedetect: debug
```

In `custom_components/iphonedetect` I have all the files needed. The logs show a lot of messages like this:

> 2020-12-13 13:15:05 DEBUG (SyncWorker_2) [custom_components.iphonedetect.device_tracker] ip n output for my_iphone is:
> 2020-12-13 13:15:05 DEBUG (SyncWorker_2) [custom_components.iphonedetect.device_tracker] Device my_iphone (192.168.1.103) is AWAY

I'm pretty new to HA; what am I missing? I have no idea how to debug this further.

**Comment by mudape** [comment]
Hi @SHxKM ,

`2020-12-13 13:15:05 DEBUG (SyncWorker_2) [custom_components.iphonedetect.device_tracker] ip n output for my_iphone is:`
Your host can't find an entry for 192.168.1.103 in its ARP-table, so your device is marked as away.


> My setup: HA is running dockerized

I suspect the HA container can't find the info needed

**Comment by SHxKM** [comment]
Thanks for the quick reply @mudape.

Any idea how can I get around that? To access the ARP table, the docker host [must be run on privileged mode and be on the host network](https://stackoverflow.com/questions/58141091/acessing-arp-table-of-host-from-docker-container), however on my OS (macOS), `network = host` is not possible in Docker.

Below is my `docker-compose.yml`, I'll try to add `privileged` to it, restart, and see if anything changes:

```
version: '3'

services:
  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant
    environment:
      # This is the required way to set a timezone on macOS and differs from the Linux compose file
      - TZ=Asia/Jerusalem
    volumes:
      - ./config:/config
    restart: unless-stopped
    ports:
      # Also required for macOS since the network directive in docker-compose does not work
      - "8123:8123"

# Add this or docker-compose will complain that it did not find the key for locally mapped volume
volumes:
  config:
```
