### ISSUE TITLE
mutiple intervals & consider_home time

### ISSUE THREAD

**Issue by shupcn** [mudape/iphonedetect#55]
Is it possible to set multiple time period for scan interval or consider_home? So that during daytime when everyone leaves for work, it is no need to constantly scan, or during night, when everyone falls asleep, same condition. And when back from work, during a certain time period, it requires much more frequent scan, so related automations can run instantly when you’re “home”. 

now I use default setting, during late night, my iPhone status will still changes to not_home. So I have to add time condition in every related automations to make them only effective during daytime.

**Comment by mudape** [comment]
Hi @shupcn 
I guess you could have multiple instances, like
```yaml
device_tracker day:
  - platform: iphonedetect
    consider_home: 30
    hosts:
      day_device: 10.0.5.41

device_tracker night:
  - platform: iphonedetect
    consider_home: 60
    hosts:
      night_device: 10.0.5.41
```

But don't see how that would help. Feels like a workaround to the real issue.
I think you have a network related issue causing devices to be "false" away.
Does it happen every night? 
Maybe the network is to busy with maintenance or other at night time?

As a first test, I would try placing the mobiles in another location with better Wi-Fi coverage to see if the problem persists.

In our home we track four phones with the default interval (12sec) and consider_home at 30sec.
Do have drops from time to time when phones are confused as to which AP to connect to.
That's solved by restarting the router and/or AP's (ASUS ZenWiFi AX), nothing in HA or iphonedetect.
