### ISSUE TITLE
Let users specify a unique_id to allow customization through UI

### ISSUE THREAD

**Issue by crixionz** [mudape/iphonedetect#69]
Hi,

First of all, thanks for this wonderful integration!!
I have a suggestion/feature request. Working with many devices and a lot of clutter isn't easy, we can all agree. 😁

Being able to specify the `unique_id` of the device_tracker-entity being created would allow the user to change the entity_id via HA's UI customization. 
To illustrate what I mean, this is what the config could look like:
```yaml
device_tracker:
  - platform: iphonedetect
    ...
    hosts:
      uniqueid1: 192.168.0.17
      uniqueid2: 192.168.0.24
or
    ...
    hosts:
      - name: hostname1 
        unique_id: uniqueid1 
        address: 192.168.0.17
      - unique_id: uniqueid2 
        name: hostname2 
        address: 192.168.0.24

```
Both of these approaches would then create `device_tracker.uniqueid1` and `device_tracker.uniqueid2` respectively. 

- The first approach uses the exact same config syntax as before and all the changes would be 'under the hood': Instead of creating an entity in HA without a unique_id and a 'hardwired' entity_id, it would now create an entity with a 'hardwired' unique_id and thereby allow customization of the icon, entity_id, friendly_name etc, via the UI.

- The second approach would mean a change in the way iphonedetect is configured. I guess that would definitely be a breaking change for existing users? I don't know, maybe its possible to retrofit. 
But it would have to have the unique_id option be _**required**_, as it is mandatory to create the entity in HA. (address is required aswell, obviously, leaving only name/friendly_name optional)

This would help setting up and organizing devices tremendously.
I'm new to python and struggle to understand the code. 😅😅 I would love to help make this, I just might not be very useful.
