### ISSUE TITLE
HASSIO in container

### ISSUE THREAD

**Issue by adlpharm** [mudape/iphonedetect#76]
Hi, I think it is not working well when you run HASSIO in a container. I received the error "IP not in range of HASS subnet". Anyway to fix it? Thanks

**Comment by mudape** [comment]
Hi @adlpharm 
I'm guessing you are not running the container on the host network?

The flow validator you got caught by is trying to avoid setting up devices that can't be tracked.
For this integration to work, HASS needs to be on the same network as the devices it should track.
If not, tracked devices will always have status Away as they can't be found in ARP.

See #74 and #73 for more clues if your host is on Mac or TrueNas

**Comment by markfrancisonly** [comment]
could this integration be modified to support a docker container with more than one network attached? When the network where my iphones are connected is attached to the home assistant container, the integration did not read the arp table from the additional network

**Comment by mudape** [comment]
Hi @markfrancisonly 

Hmm maybe changing default network in home-assistant?
![image](https://user-images.githubusercontent.com/26150341/181525854-914ee94a-9532-4f9c-b9b4-e629516d1235.jpeg)

Else editing the "look up" command and specify the interface. 

I only have one network in my household, can't really try myself

**Comment by markfrancisonly** [comment]
wait... it works out of the box! my bad... home assistant was hanging on to an older version of my iphonedetect entities from the mariadb database? deleted my history database and the duplicate device_trackers are gone, and now I'm looking at the correct entities...

e.g.
```
version: "3"
services:

  homeassistant:
    image: homeassistant/home-assistant:stable
    container_name: homeassistant
    restart: always

    volumes:
      - ./homeassistant:/config
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    
    networks:
      vlan1:
        ipv4_address: 192.168.1.100
      vlan2:
        ipv4_address: 192.168.2.100
      homeassistant_internal:

networks:
  homeassistant_internal:
    name: homeassistant_internal
    internal: true
  vlan1:
    external: true
  vlan2:
    external: true
```

iphonedetect is now able to find devices from both vlan1 and vlan2 networks
