### ISSUE TITLE
Suggestion!

### ISSUE THREAD

**Issue by pointlevel** [mudape/iphonedetect#86]
Thanks for this wonderful script that really works. 

I wonder if that would be possible to add a function to this script for switching the scanner on and off from homeassistant. 

for example:
```
device_tracker:
  - platform: iphonedetect
    consider_home: 30
    interval_seconds: 12
    new_device_defaults:
      track_new_devices: false
    toggle_entity_id: input_boolean.toggle_presence_scan
    hosts:
      my_phone: 102.168.1.1
```

My thoughts on this is that when no doors is opened, nobody can physically go in or out, and the scan dont need to be active. 
And as soon as any door is opened, the boolean turns on by an automation and the scanner runs as normal with intervals as long as the boolean is 'on'. If the scanner starts immediately when the boolean turns on, i think the arrival-detection would be faster also, because you dont need to wait between 0-12 seconds before it runs.

Thanks.
